# Generated by Django 5.2.4 on 2025-07-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnj', models.CharField(max_length=30, unique=True, verbose_name='Número CNJ')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('vara', models.CharField(max_length=255, verbose_name='Vara')),
                ('tribunal', models.CharField(blank=True, max_length=50, verbose_name='Tribunal')),
                ('valor_causa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Causa')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_polo', models.CharField(choices=[('ATIVO', 'Polo Ativo'), ('PASSIVO', 'Polo Passivo')], max_length=7, verbose_name='Tipo de Polo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa')),
                ('documento', models.CharField(max_length=20, verbose_name='CPF / CNPJ')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='contratos.processojudicial')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número do Contrato')),
                ('valor_total_devido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Devido')),
                ('parcelas_em_aberto', models.IntegerField(verbose_name='Parcelas em Aberto')),
                ('data_contrato', models.DateField(verbose_name='Data do Contrato')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='contratos.processojudicial')),
            ],
        ),
    ]
