# Generated by Django 5.2.4 on 2025-07-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('sexo_biologico', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher')], max_length=1, verbose_name='Sexo Biológico')),
            ],
            options={
                'verbose_name': 'Devedor',
                'verbose_name_plural': 'Devedores',
            },
        ),
        migrations.CreateModel(
            name='ProcessoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnj', models.CharField(max_length=25, unique=True, verbose_name='Número CNJ')),
                ('valor_causa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Causa')),
                ('vara', models.CharField(max_length=255, verbose_name='Vara')),
                ('tribunal', models.CharField(max_length=255, verbose_name='Tribunal')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('valor_total_devido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total Devido')),
                ('parcelas_em_aberto', models.PositiveIntegerField(verbose_name='Parcelas em Aberto')),
                ('data_contrato', models.DateField(blank=True, null=True, verbose_name='Data do Contrato')),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.devedor', verbose_name='Devedor')),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.processojudicial', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
