# Generated by Django 5.2.4 on 2025-07-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Status')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Status Processual',
                'verbose_name_plural': 'Status Processuais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.statusprocessual', verbose_name='Status Processual'),
        ),
    ]
