# Generated by Django 5.2.4 on 2025-07-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_statusprocessual_processojudicial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='busca_ativa',
            field=models.BooleanField(default=False, help_text='Se marcado, o sistema buscará andamentos para este processo automaticamente.', verbose_name='Busca Ativa'),
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='contratos.processojudicial')),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
                'ordering': ['-data'],
                'unique_together': {('processo', 'data', 'descricao')},
            },
        ),
    ]
