# Generated by Django 5.2.4 on 2025-07-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_processojudicial_busca_ativa_andamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_processuais', to='contratos.processojudicial'),
        ),
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('numero_oab', models.CharField(max_length=20, verbose_name='Número OAB')),
                ('uf_oab', models.CharField(max_length=2, verbose_name='UF OAB')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogados', to='contratos.parte')),
            ],
        ),
        migrations.CreateModel(
            name='AndamentoProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='contratos.processojudicial')),
            ],
            options={
                'verbose_name': 'Andamento Processual',
                'verbose_name_plural': 'Andamentos Processuais',
                'ordering': ['-data'],
                'unique_together': {('processo', 'data', 'descricao')},
            },
        ),
        migrations.DeleteModel(
            name='Andamento',
        ),
    ]
