# Generated by Django 5.2.4 on 2025-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_parte_processo_advogado_andamentoprocessual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='advogados_info',
            field=models.TextField(blank=True, null=True, verbose_name='Informações dos Advogados'),
        ),
    ]
