# Generated by Django 5.2.4 on 2025-07-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_parte_advogados_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusprocessual',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
