# Generated by Django 5.2.4 on 2025-07-21 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_statusprocessual_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Carteira')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='carteira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='contratos.carteira', verbose_name='Carteira'),
        ),
        migrations.CreateModel(
            name='ParteProcessoAdvogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.advogado')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.parte')),
            ],
            options={
                'verbose_name': 'Relação Parte-Advogado',
                'verbose_name_plural': 'Relações Parte-Advogado',
                'unique_together': {('parte', 'advogado')},
            },
        ),
    ]
