# Generated by Django 5.2.4 on 2025-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_carteira_processojudicial_carteira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField()),
                ('cor_fundo', models.CharField(default='#264653', max_length=7)),
                ('cor_fonte', models.CharField(default='#ffffff', max_length=7)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
    ]
