# Generated by Django 5.2.4 on 2025-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_etiqueta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='contratos.etiqueta', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='cor_fonte',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor da Fonte'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='cor_fundo',
            field=models.CharField(default='#417690', max_length=7, verbose_name='Cor de Fundo'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Etiqueta'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem'),
        ),
    ]
