# Generated by Django 5.2.4 on 2025-07-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_alter_etiqueta_options_processojudicial_etiquetas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processojudicial',
            name='etiquetas',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
