# Generated by Django 5.2.4 on 2025-07-23 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_remove_processojudicial_etiquetas_delete_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cor_fundo', models.CharField(default='#417690', max_length=7, verbose_name='Cor de Fundo')),
                ('cor_fonte', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor da Fonte')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='contratos.etiqueta', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='AndamentoProcessualAdvogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.advogado')),
                ('andamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.andamentoprocessual')),
            ],
            options={
                'verbose_name': 'Relação Andamento-Advogado',
                'verbose_name_plural': 'Relações Andamento-Advogado',
                'unique_together': {('andamento', 'advogado')},
            },
        ),
    ]
