# Generated by Django 5.2.4 on 2025-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_etiqueta_processojudicial_etiquetas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem'),
        ),
    ]
