# Generated by Django 5.2.4 on 2025-07-28 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_alter_etiqueta_options_etiqueta_ordem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeTarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Lista de Tarefas',
                'verbose_name_plural': 'Listas de Tarefas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_limite', models.DateTimeField(verbose_name='Data Limite')),
                ('alerta_valor', models.PositiveIntegerField(default=1, verbose_name='Alerta')),
                ('alerta_unidade', models.CharField(choices=[('D', 'Dias antes'), ('H', 'Horas antes')], default='D', max_length=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='contratos.processojudicial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
                'ordering': ['data_limite'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='M', max_length=1)),
                ('concluida', models.BooleanField(default=False)),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.listadetarefas', verbose_name='Lista')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='contratos.processojudicial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data'],
            },
        ),
    ]
