# Generated by Django 5.2.4 on 2025-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_listadetarefas_prazo_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='data_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_prescricao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prescrição'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Causa'),
        ),
        migrations.AlterField(
            model_name='andamentoprocessual',
            name='detalhes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='parcelas_em_aberto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcelas em Aberto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total_devido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total Devido'),
        ),
    ]
