# Generated by Django 5.2.4 on 2025-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_remove_contrato_data_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor da Causa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total_devido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Total Devido'),
        ),
        migrations.AlterField(
            model_name='processojudicial',
            name='valor_causa',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor da Causa'),
        ),
    ]
