# Generated by Django 5.2.4 on 2025-11-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_alter_contrato_valor_causa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
