# Generated by Django 5.2.4 on 2025-11-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_processojudicial_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=255, verbose_name='Texto da Pergunta/Critério')),
                ('tipo_campo', models.CharField(choices=[('OPCOES', 'Opções (dropdown)'), ('TEXTO', 'Texto Curto'), ('TEXTO_LONGO', 'Texto Longo (observações)'), ('DATA', 'Data'), ('PROCESSO_VINCULADO', 'Interface de Processos Vinculados')], default='OPCOES', max_length=20, verbose_name='Tipo de Campo de Resposta')),
                ('is_primeira_questao', models.BooleanField(default=False, help_text='Marque apenas uma questão como a primeira. Será o ponto de partida da árvore.', verbose_name='É a primeira questão da análise?')),
                ('ordem', models.PositiveIntegerField(default=10, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Questão da Análise',
                'verbose_name_plural': '1. Questões da Análise',
                'ordering': ['ordem', 'texto_pergunta'],
            },
        ),
        migrations.AlterModelOptions(
            name='prazo',
            options={},
        ),
        migrations.RemoveField(
            model_name='processojudicial',
            name='endereco',
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(max_length=255, verbose_name='Texto da Opção de Resposta')),
                ('proxima_questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veio_de_opcao', to='contratos.questaoanalise', verbose_name='Próxima Questão (se esta opção for escolhida)')),
                ('questao_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='contratos.questaoanalise', verbose_name='Questão de Origem')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': '2. Opções de Respostas',
                'ordering': ['questao_origem', 'texto_resposta'],
            },
        ),
    ]
