# Generated by Django 5.2.4 on 2025-12-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_questaoanalise_alter_prazo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prazo',
            options={'ordering': ['data_limite'], 'verbose_name': 'Prazo', 'verbose_name_plural': 'Prazos'},
        ),
        migrations.CreateModel(
            name='AnaliseProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField(default=dict, verbose_name='Respostas da Análise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo_judicial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_processo', to='contratos.processojudicial', verbose_name='Processo Judicial')),
            ],
            options={
                'verbose_name': 'Análise de Processo',
                'verbose_name_plural': 'Análises de Processos',
            },
        ),
    ]
