# Generated by Django 5.2.4 on 2025-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_alter_prazo_options_analiseprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoanalise',
            name='chave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Chave de Referência (Slug)'),
        ),
    ]
