# Generated by Django 5.2.4 on 2025-12-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_analiseprocesso_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaoanalise',
            name='tipo_campo',
            field=models.CharField(choices=[('OPCOES', 'Opções (dropdown)'), ('TEXTO', 'Texto Curto'), ('TEXTO_LONGO', 'Texto Longo (observações)'), ('DATA', 'Data'), ('PROCESSO_VINCULADO', 'Interface de Processos Vinculados'), ('CONTRATOS_MONITORIA', 'Seleção de Contratos para Monitória')], default='OPCOES', max_length=20, verbose_name='Tipo de Campo de Resposta'),
        ),
    ]
