# Generated by Django 5.2.4 on 2025-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_alter_questaoanalise_tipo_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='nao_judicializado',
            field=models.BooleanField(default=True, editable=False, verbose_name='Não Judicializado'),
        ),
        migrations.AlterField(
            model_name='processojudicial',
            name='cnj',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Número CNJ'),
        ),
    ]
