# Generated by Django 5.2.4 on 2025-12-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_processojudicial_nao_judicializado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processojudicial',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor da Causa'),
        ),
        migrations.AlterField(
            model_name='processojudicial',
            name='vara',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vara'),
        ),
    ]
