# Generated by Django 5.2.4 on 2025-12-04 16:39

from django.db import migrations
from django.db.models import Q

def correct_nao_judicializado_values(apps, schema_editor):
    """
    Corrige os valores do campo 'nao_judicializado' para todos os Processos Judiciais existentes.
    Define como False se houver um CNJ, e True caso contrário.
    """
    ProcessoJudicial = apps.get_model('contratos', 'ProcessoJudicial')
    db_alias = schema_editor.connection.alias

    # Processos com CNJ preenchido (não nulo e não vazio) devem ter nao_judicializado = False
    ProcessoJudicial.objects.using(db_alias).filter(
        Q(cnj__isnull=False) & ~Q(cnj__exact='')
    ).update(nao_judicializado=False)

    # Processos sem CNJ (nulo ou string vazia) devem ter nao_judicializado = True
    ProcessoJudicial.objects.using(db_alias).filter(
        Q(cnj__isnull=True) | Q(cnj__exact='')
    ).update(nao_judicializado=True)

class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_alter_processojudicial_valor_causa_and_more'),
    ]

    operations = [
        migrations.RunPython(correct_nao_judicializado_values, migrations.RunPython.noop),
    ]
