# Generated by Django 5.2.4 on 2025-12-04 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_fix_nao_judicializado_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='delegado_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_delegados', to=settings.AUTH_USER_MODEL, verbose_name='Delegado Para'),
        ),
    ]
