# Generated by Django 5.2.4 on 2025-12-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_processojudicial_delegado_para'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusprocessual',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Classe Processual', 'verbose_name_plural': 'Classes Processuais'},
        ),
    ]
