# Generated by Django 5.2.4 on 2025-12-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_alter_statusprocessual_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processojudicial',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.statusprocessual', verbose_name='Classe Processual'),
        ),
    ]
