# Generated by Django 5.2.4 on 2025-12-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_buscaativaconfig'),
        ('contratos', '0027_alter_processojudicial_status'),
    ]

    operations = [
    ]
