# Generated by Django 5.2.4 on 2025-12-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_merge_20251205_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prazo',
            options={},
        ),
    ]
