# Generated by Django 5.2.4 on 2025-12-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_alter_prazo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parte',
            options={'ordering': ['tipo_polo', 'id']},
        ),
    ]
