# Generated by Django 5.2.4 on 2025-12-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_alter_parte_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvogadoPassivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('uf_oab', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF da OAB')),
                ('oab_numero', models.CharField(max_length=10, verbose_name='Número da OAB')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('agendar_ligacao_em', models.DateTimeField(blank=True, null=True, verbose_name='Agendar ligação em')),
                ('lembrete_enviado', models.BooleanField(default=False, verbose_name='Lembrete enviado')),
                ('parte', models.ForeignKey(limit_choices_to={'tipo_polo': 'PASSIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='advogados_passivos', to='contratos.parte')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogados_passivos', to='contratos.processojudicial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo contato')),
            ],
            options={
                'verbose_name': 'Advogado da Parte Passiva',
                'verbose_name_plural': 'Advogados da Parte Passiva',
                'ordering': ['nome'],
            },
        ),
    ]
