# Generated by Django 5.2.4 on 2025-12-07 16:21

import contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0033_advogadopassivo_acordo_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('arquivo', models.FileField(upload_to=contratos.models.processo_arquivo_upload_path, verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='contratos.processojudicial')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
