# Generated by Django 5.2.4 on 2025-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0034_processoarquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('monitoria_inicial', 'Monitoria Inicial'), ('cobranca_judicial', 'Cobrança Judicial')], help_text='Identificador usado no backend para localizar o modelo.', max_length=50, unique=True, verbose_name='Chave')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome exibido')),
                ('arquivo', models.FileField(help_text='Envie o arquivo .docx que servirá como minuta.', upload_to='documentos_modelo/', verbose_name='Arquivo DOCX')),
                ('descricao', models.TextField(blank=True, help_text='Informações extras sobre placeholders ou variantes.', verbose_name='Orientações')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Documento Modelo',
                'verbose_name_plural': 'Documentos Modelo',
                'ordering': ['slug', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='advogadopassivo',
            name='acordo_status',
            field=models.CharField(blank=True, choices=[('PROPOR', 'Propor'), ('PROPOSTO', 'Proposto'), ('FIRMADO', 'Firmado'), ('RECUSADO', 'Recusado')], max_length=10, verbose_name='Acordo'),
        ),
    ]
