# Generated by Django 5.2.4 on 2025-12-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0035_documentomodelo_alter_advogadopassivo_acordo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='obito',
            field=models.BooleanField(default=False, verbose_name='Óbito'),
        ),
    ]
