# Generated by Django 5.2.4 on 2025-12-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0036_parte_obito'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='viabilidade',
            field=models.CharField(choices=[('VIAVEL', 'Viável'), ('INVIAVEL', 'Inviável'), ('INCONCLUSIVO', 'Inconclusivo')], default='INCONCLUSIVO', help_text='Indique se o processo está financeiramente viável, inviável ou inconclusivo.', max_length=15, verbose_name='Viabilidade'),
        ),
    ]
