# Generated by Django 5.2.4 on 2025-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0037_processojudicial_viabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processojudicial',
            name='viabilidade',
            field=models.CharField(blank=True, choices=[('', '---'), ('VIAVEL', 'Viável'), ('INVIAVEL', 'Inviável'), ('INCONCLUSIVO', 'Inconclusivo')], default='', help_text='Indique se o processo está financeiramente viável, inviável ou inconclusivo.', max_length=15, verbose_name='Viabilidade'),
        ),
    ]
