# Generated by Django 5.2.4 on 2025-12-14 12:05

from django.db import migrations, models


def _populate_para_supervisionar(apps, schema_editor):
    AnaliseProcesso = apps.get_model('contratos', 'AnaliseProcesso')
    for analise in AnaliseProcesso.objects.all():
        respostas = getattr(analise, 'respostas', {}) or {}
        processos_vinculados = respostas.get('processos_vinculados')
        flag = False
        if isinstance(processos_vinculados, list):
            for item in processos_vinculados:
                if isinstance(item, dict) and item.get('supervisionado'):
                    flag = True
                    break
        if flag:
            AnaliseProcesso.objects.filter(pk=analise.pk).update(para_supervisionar=True)


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0038_alter_processojudicial_viabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseprocesso',
            name='para_supervisionar',
            field=models.BooleanField(default=False, help_text='Ativo quando algum processo vinculado estiver marcado para supervisão.', verbose_name='Marcar para Supervisionar'),
        ),
        migrations.RunPython(
            code=_populate_para_supervisionar,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
