# Generated by Django 5.2.4 on 2025-12-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0040_processojudicial_soma_contratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomodelo',
            name='tipos_peticao',
            field=models.JSONField(blank=True, default=list, help_text='Lista ordenada dos nomes que aparecerão no dropdown da aba Petições.', verbose_name='Tipos de Petição'),
        ),
    ]
