# Generated by Django 5.2.4 on 2025-12-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0041_documentomodelo_tipos_peticao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Petição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Petição',
                'verbose_name_plural': 'Tipos de Petição',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='documentomodelo',
            name='tipos_peticao',
        ),
    ]
