# Generated by Django 5.2.4 on 2025-12-23 16:54

import contratos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0042_tipopeticao_remove_documentomodelo_tipos_peticao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboDocumentoPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('FIXO', 'Fixo/Obrigatório'), ('CONTRATO', 'Por contrato'), ('ANEXO', 'Anexo opcional')], default='FIXO', max_length=10, verbose_name='Categoria')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('label_template', models.CharField(help_text="Use 'xxxxxxxxx' para o placeholder de contrato.", max_length=255, verbose_name='Rótulo esperado')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Palavras que devem estar no nome do arquivo (case-insensitive).', verbose_name='Palavras-chave')),
                ('placeholder', models.CharField(blank=True, default='xxxxxxxxx', max_length=32, verbose_name='Placeholder de contrato')),
                ('obrigatorio', models.BooleanField(default=True, help_text="Define se a ausência gera item em 'faltantes'.", verbose_name='Obrigatório')),
                ('tipo_peticao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_patterns', to='contratos.tipopeticao')),
            ],
            options={
                'verbose_name': 'Configuração de documento para o combo',
                'verbose_name_plural': 'Configurações de combo',
                'ordering': ['tipo_peticao', 'categoria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ZipGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to=contratos.models.peticao_zip_upload_path, verbose_name='Arquivo ZIP')),
                ('missing', models.JSONField(blank=True, default=list)),
                ('contratos', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zips_gerados', to='contratos.processoarquivo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zips_peticao', to='contratos.processojudicial')),
                ('tipo_peticao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zips_gerados', to='contratos.tipopeticao')),
            ],
            options={
                'verbose_name': 'ZIP gerado para petição',
                'verbose_name_plural': 'ZIPs gerados para petições',
                'ordering': ['-criado_em'],
            },
        ),
    ]
