# Generated by Django 5.2.4 on 2025-12-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0043_combodocumentopattern_zipgerado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPeticaoAnexoContinua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='peticoes/anexos_continuos/', verbose_name='Arquivo do combo')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome exibido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tipo_peticao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_continuos', to='contratos.tipopeticao')),
            ],
            options={
                'verbose_name': 'Anexo contínuo',
                'verbose_name_plural': 'Anexos contínuos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
