# Generated by Django 5.2.4 on 2025-12-26 16:43

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0044_tipopeticaoanexocontinua'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopeticao',
            name='key',
            field=models.CharField(db_index=True, default=contratos.models._generate_tipo_peticao_key, editable=False, max_length=36, verbose_name='Chave única'),
        ),
    ]
