# Generated by Django 5.2.4 on 2025-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0045_tipopeticao_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoarquivo',
            name='protocolado_no_tribunal',
            field=models.BooleanField(default=False, help_text='Marque para indicar que este arquivo foi protocolado no tribunal.', verbose_name='Confirmado protocolo no tribunal'),
        ),
        migrations.AlterField(
            model_name='documentomodelo',
            name='slug',
            field=models.CharField(help_text='Identificador usado no backend para localizar o modelo. Valores padrão: monitoria_inicial, cobranca_judicial, habilitacao (adicione outros conforme necessário).', max_length=50, unique=True, verbose_name='Chave'),
        ),
    ]
