# Generated by Django 5.2.4 on 2026-01-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0046_processoarquivo_protocolado_no_tribunal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
