# Generated by Django 5.2.4 on 2026-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0047_tarefa_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazo',
            name='data_limite_origem',
            field=models.DateField(blank=True, null=True, verbose_name='Data limite de origem'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_origem',
            field=models.DateField(blank=True, null=True, verbose_name='Data de origem'),
        ),
    ]
