# Generated by Django 5.2.4 on 2026-01-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0049_herdeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='fonte_alias',
            field=models.CharField(blank=True, help_text="Alias da conexão do banco que será utilizada para importar cadastros (ex.: carteira, carteira_bcs, carteira_teste). Deixe em branco para usar a conexão padrão 'carteira'.", max_length=64, verbose_name='Fonte da Carteira'),
        ),
    ]
