# Generated by Django 5.2.4 on 2026-01-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0053_contrato_custas'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='heranca_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Herança'),
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='heranca_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Herança (R\\$)'),
        ),
    ]
