# Generated by Django 5.2.4 on 2026-01-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0054_processojudicial_heranca_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='obito_cidade',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cidade do Óbito'),
        ),
        migrations.AddField(
            model_name='parte',
            name='obito_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Óbito'),
        ),
        migrations.AddField(
            model_name='parte',
            name='obito_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF do Óbito'),
        ),
    ]
