# Generated by Django 5.2.4 on 2026-01-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0055_parte_obito_cidade_parte_obito_data_parte_obito_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='obito_idade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade no Óbito'),
        ),
    ]
