# Generated by Django 5.2.4 on 2026-02-03 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0058_tarefa_criado_por_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processoarquivo',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='contratos.tarefa'),
        ),
        migrations.CreateModel(
            name='TarefaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_mensagens', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='contratos.tarefa')),
            ],
            options={
                'verbose_name': 'Mensagem da Tarefa',
                'verbose_name_plural': 'Mensagens da Tarefa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='processoarquivo',
            name='mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='contratos.tarefamensagem'),
        ),
    ]
