# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0059_processoarquivo_tarefa_tarefamensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='checagem_sistemas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Checagem de Sistemas'),
        ),
    ]
