# Generated by Django 5.2.4 on 2026-02-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0060_processojudicial_checagem_sistemas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processoarquivo',
            name='prazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='contratos.prazo'),
        ),
        migrations.CreateModel(
            name='PrazoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_mensagens', to=settings.AUTH_USER_MODEL)),
                ('prazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='contratos.prazo')),
            ],
            options={
                'verbose_name': 'Mensagem do Prazo',
                'verbose_name_plural': 'Mensagens do Prazo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='processoarquivo',
            name='prazo_mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='contratos.prazomensagem'),
        ),
    ]
