# Generated by Django 5.2.4 on 2026-02-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0061_processoarquivo_prazo_prazomensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazo',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='contratos.processojudicial'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='contratos.processojudicial'),
        ),
    ]
