# Generated by Django 5.2.4 on 2026-02-13 10:33

from django.db import migrations, models


def populate_carteiras_vinculadas(apps, schema_editor):
    ProcessoJudicial = apps.get_model('contratos', 'ProcessoJudicial')
    NumeroCnj = apps.get_model('contratos', 'ProcessoJudicialNumeroCnj')
    through = ProcessoJudicial.carteiras_vinculadas.through

    existing_pairs = set(
        through.objects.all().values_list('processojudicial_id', 'carteira_id')
    )
    rows_to_create = []

    processos = ProcessoJudicial.objects.all().only('id', 'carteira_id')
    for processo in processos.iterator(chunk_size=1000):
        carteira_ids = set()
        if processo.carteira_id:
            carteira_ids.add(processo.carteira_id)
        carteira_ids.update(
            NumeroCnj.objects.filter(processo_id=processo.id)
            .exclude(carteira_id__isnull=True)
            .values_list('carteira_id', flat=True)
            .distinct()
        )
        for carteira_id in carteira_ids:
            pair = (processo.id, carteira_id)
            if pair in existing_pairs:
                continue
            existing_pairs.add(pair)
            rows_to_create.append(
                through(processojudicial_id=processo.id, carteira_id=carteira_id)
            )

    if rows_to_create:
        through.objects.bulk_create(rows_to_create, ignore_conflicts=True)


def reverse_populate_carteiras_vinculadas(apps, schema_editor):
    ProcessoJudicial = apps.get_model('contratos', 'ProcessoJudicial')
    through = ProcessoJudicial.carteiras_vinculadas.through
    through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0065_carteira_usuario_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='carteiras_vinculadas',
            field=models.ManyToManyField(blank=True, related_name='processos_multicarteira', to='contratos.carteira', verbose_name='Carteiras vinculadas'),
        ),
        migrations.RunPython(
            populate_carteiras_vinculadas,
            reverse_code=reverse_populate_carteiras_vinculadas,
        ),
    ]
