# Generated by Django 5.2.4 on 2026-02-13 10:48

import django.db.models.deletion
from django.db import migrations, models


def _normalize_cnj_digits(value):
    return "".join(ch for ch in str(value or "") if ch.isdigit())


def _populate_numero_cnj_links(apps, schema_editor):
    ProcessoJudicial = apps.get_model('contratos', 'ProcessoJudicial')
    ProcessoJudicialNumeroCnj = apps.get_model('contratos', 'ProcessoJudicialNumeroCnj')
    Parte = apps.get_model('contratos', 'Parte')
    AndamentoProcessual = apps.get_model('contratos', 'AndamentoProcessual')

    numero_by_processo = {}
    for processo in ProcessoJudicial.objects.only('id', 'cnj').iterator():
        target = None
        numeros_qs = ProcessoJudicialNumeroCnj.objects.filter(processo_id=processo.id).order_by('-criado_em', '-id')
        current_digits = _normalize_cnj_digits(processo.cnj)
        if current_digits:
            for numero in numeros_qs.only('id', 'cnj'):
                if _normalize_cnj_digits(numero.cnj) == current_digits:
                    target = numero
                    break
        if not target:
            target = numeros_qs.only('id').first()
        if target:
            numero_by_processo[processo.id] = target.id

    for processo_id, numero_cnj_id in numero_by_processo.items():
        Parte.objects.filter(processo_id=processo_id, numero_cnj_id__isnull=True).update(numero_cnj_id=numero_cnj_id)
        AndamentoProcessual.objects.filter(processo_id=processo_id, numero_cnj_id__isnull=True).update(numero_cnj_id=numero_cnj_id)


def _clear_numero_cnj_links(apps, schema_editor):
    Parte = apps.get_model('contratos', 'Parte')
    AndamentoProcessual = apps.get_model('contratos', 'AndamentoProcessual')
    Parte.objects.update(numero_cnj_id=None)
    AndamentoProcessual.objects.update(numero_cnj_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0066_processojudicial_carteiras_vinculadas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='andamentoprocessual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='andamentoprocessual',
            name='numero_cnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andamentos_processuais', to='contratos.processojudicialnumerocnj', verbose_name='Número CNJ'),
        ),
        migrations.AddField(
            model_name='parte',
            name='numero_cnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_processuais', to='contratos.processojudicialnumerocnj', verbose_name='Número CNJ'),
        ),
        migrations.RunPython(_populate_numero_cnj_links, _clear_numero_cnj_links),
        migrations.AlterUniqueTogether(
            name='andamentoprocessual',
            unique_together={('processo', 'numero_cnj', 'data', 'descricao')},
        ),
    ]
