# Generated by Django 5.2.4 on 2026-02-13 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0067_alter_andamentoprocessual_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='cor_grafico',
            field=models.CharField(
                default='#417690',
                help_text='Cor usada nos gráficos e no diagrama de interseções desta carteira.',
                max_length=7,
                validators=[django.core.validators.RegexValidator(message='Informe uma cor HEX válida no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')],
                verbose_name='Cor nos gráficos',
            ),
        ),
    ]
