# Generated by Django 5.2.4 on 2026-02-20 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0069_prazo_concluido_em_prazo_concluido_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaAnaliseLoteSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do lote')),
                ('identificadores', models.TextField(verbose_name='CNJs/CPFs')),
                ('ultimo_importado_em', models.DateTimeField(blank=True, null=True, verbose_name='Última importação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('carteira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_lotes_salvos', to='contratos.carteira', verbose_name='Carteira sugerida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_lotes_salvos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lote salvo de demandas',
                'verbose_name_plural': 'Lotes salvos de demandas',
                'ordering': ['-atualizado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nome'), name='uniq_demandas_lote_salvo_usuario_nome')],
            },
        ),
    ]
