# Generated by Django 5.2.4 on 2026-02-21 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0070_demandaanaliselotesalvo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('prioridade_default_carteira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contratos.carteira', verbose_name='Carteira padrão (KPI Prioridade)')),
            ],
            options={
                'verbose_name': 'Configuração Global de KPI',
                'verbose_name_plural': 'Configuração Global de KPI',
            },
        ),
    ]
