# Generated by Django 5.2.4 on 2026-02-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0071_kpiglobalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogadopassivo',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='advogadopassivo',
            name='oab_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da OAB'),
        ),
        migrations.AlterField(
            model_name='advogadopassivo',
            name='uf_oab',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF da OAB'),
        ),
    ]
