# Generated by Django 5.2.4 on 2026-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0072_alter_advogadopassivo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoanalise',
            name='habilita_supervisao',
            field=models.BooleanField(default=False, help_text='Quando marcado, o botão Supervisionar passa a ser exibido a partir desta questão.', verbose_name='Habilita Supervisionar'),
        ),
    ]
