# Generated by Django 5.2.4 on 2026-02-26 20:59

import django.db.models.deletion
from django.db import migrations, models


def _normalize_documento_digits(value):
    return ''.join(ch for ch in str(value or '') if ch.isdigit())


def _backfill_parte_pessoa(apps, schema_editor):
    Pessoa = apps.get_model('contratos', 'Pessoa')
    Parte = apps.get_model('contratos', 'Parte')

    pessoas_cache = {}
    for pessoa in Pessoa.objects.exclude(documento_normalizado__isnull=True).only('id', 'documento_normalizado'):
        pessoas_cache[pessoa.documento_normalizado] = pessoa.id

    for parte in Parte.objects.order_by('id').iterator():
        documento = (parte.documento or '').strip()
        documento_normalizado = _normalize_documento_digits(documento)
        if not documento_normalizado:
            continue

        pessoa_id = pessoas_cache.get(documento_normalizado)
        if pessoa_id:
            pessoa = Pessoa.objects.get(pk=pessoa_id)
            changed = False
            nome = (parte.nome or '').strip()
            if nome and pessoa.nome != nome:
                pessoa.nome = nome
                changed = True
            tipo_pessoa = (parte.tipo_pessoa or '').strip()
            if tipo_pessoa and pessoa.tipo_pessoa != tipo_pessoa:
                pessoa.tipo_pessoa = tipo_pessoa
                changed = True
            if documento and pessoa.documento != documento:
                pessoa.documento = documento
                changed = True
            if changed:
                pessoa.save()
        else:
            pessoa = Pessoa.objects.create(
                nome=(parte.nome or '').strip(),
                tipo_pessoa=(parte.tipo_pessoa or '').strip(),
                documento=documento,
                documento_normalizado=documento_normalizado,
            )
            pessoas_cache[documento_normalizado] = pessoa.id

        if parte.pessoa_id != pessoa.id:
            parte.pessoa_id = pessoa.id
            parte.save(update_fields=['pessoa'])


def _clear_parte_pessoa(apps, schema_editor):
    Parte = apps.get_model('contratos', 'Parte')
    Parte.objects.update(pessoa=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0073_questaoanalise_habilita_supervisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome / Razão Social')),
                ('tipo_pessoa', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ')),
                ('documento_normalizado', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='CPF / CNPJ (normalizado)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.AddField(
            model_name='parte',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_processuais', to='contratos.pessoa', verbose_name='Pessoa'),
        ),
        migrations.RunPython(_backfill_parte_pessoa, _clear_parte_pessoa),
    ]
