# Generated by Django 5.2.4 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0074_pessoa_parte_pessoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="documento_titular",
            field=models.CharField(
                blank=True,
                help_text="Preenchido automaticamente para vincular o contrato à pessoa no card.",
                max_length=20,
                verbose_name="CPF/CNPJ titular",
            ),
        ),
    ]
