# Generated by Django 5.2.4 on 2026-03-02 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0076_tarefanotificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndamentoProcessualPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('texto_bruto', models.TextField(verbose_name='Texto bruto')),
                ('data_andamento', models.DateTimeField(verbose_name='Data do andamento')),
                ('data_deteccao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de detecção')),
                ('prazo_extraido', models.DateField(blank=True, null=True, verbose_name='Prazo extraído')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('pendente_respondido_manualmente', 'Pendente respondido manualmente'), ('tratado', 'Tratado')], default='novo', max_length=40, verbose_name='Status')),
                ('tratado_em', models.DateTimeField(blank=True, null=True, verbose_name='Tratado em')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('andamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendencia', to='contratos.andamentoprocessual', verbose_name='Andamento')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos_pendentes', to='contratos.processojudicial', verbose_name='Processo')),
                ('tratado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andamentos_processuais_tratados', to=settings.AUTH_USER_MODEL, verbose_name='Tratado por')),
            ],
            options={
                'verbose_name': 'Andamento Processual Pendente',
                'verbose_name_plural': 'Andamentos Processuais Pendentes',
                'ordering': ['-data_deteccao', '-id'],
            },
        ),
    ]
