# Generated by Codex on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0080_backfill_pessoa_obito'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicialnumerocnj',
            name='pertinencia_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NEUTRO', 'Pertinência'),
                    ('PERTINENTE', 'Pertinente Atuar'),
                    ('IMPERTINENTE', 'Impertinente Atuar'),
                ],
                default='NEUTRO',
                max_length=15,
                verbose_name='Pertinência',
            ),
        ),
        migrations.AddField(
            model_name='processojudicialnumerocnj',
            name='pertinencia_periodicidade_dias',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='Periodicidade (dias)',
            ),
        ),
        migrations.AddField(
            model_name='processojudicialnumerocnj',
            name='pertinencia_proximo_em',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Próxima revisita',
            ),
        ),
    ]
