# Generated by Django 5.2.4 on 2026-03-09 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0081_cnj_pertinencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoCpfLoteSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='Nome da lista')),
                ('cpfs', models.TextField(verbose_name='CPFs')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='Compartilhado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_cpf_lotes_salvos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lista salva de CPFs',
                'verbose_name_plural': 'Listas salvas de CPFs',
                'ordering': ['-atualizado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('criado_por', 'nome'), name='uniq_processo_cpf_lote_criado_por_nome')],
            },
        ),
    ]
