# Generated by Django 5.2.4 on 2026-03-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0082_processocpflotesalvo'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE contratos_processocpflotesalvo "
                "ADD COLUMN IF NOT EXISTS atualizado_em timestamp with time zone"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
