# Generated by Django 5.2.4 on 2026-03-16 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import contratos.models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0085_fix_processocpflotesalvo_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoCnjLoteSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=contratos.models._generate_processo_cpf_lote_token, editable=False, max_length=32, unique=True, verbose_name='Token')),
                ('nome', models.CharField(max_length=140, verbose_name='Nome da lista')),
                ('cnjs', models.TextField(verbose_name='CNJs')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='Compartilhado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_cnj_lotes_salvos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lista salva de CNJs',
                'verbose_name_plural': 'Listas salvas de CNJs',
                'ordering': ['-atualizado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('criado_por', 'nome'), name='uniq_processo_cnj_lote_criado_por_nome')],
            },
        ),
    ]
