# Generated by Django 5.2.4 on 2026-03-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0086_processocnjlotesalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processocnjlotesalvo',
            name='oculto_supervisor',
            field=models.BooleanField(default=False, verbose_name='Oculto para supervisores'),
        ),
        migrations.AddField(
            model_name='processocpflotesalvo',
            name='oculto_supervisor',
            field=models.BooleanField(default=False, verbose_name='Oculto para supervisores'),
        ),
    ]
