# Generated by Django 5.2.4 on 2026-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0087_processocnjlotesalvo_oculto_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefanotificacao',
            name='autor_nome',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Autor exibido'),
        ),
        migrations.AddField(
            model_name='tarefanotificacao',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='tarefanotificacao',
            name='justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='tarefanotificacao',
            name='tipo',
            field=models.CharField(
                choices=[('recebida', 'Recebida'), ('devolutiva', 'Devolutiva')],
                db_index=True,
                default='recebida',
                max_length=20,
                verbose_name='Tipo',
            ),
        ),
        migrations.AddField(
            model_name='tarefanotificacao',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Título'),
        ),
        migrations.RemoveConstraint(
            model_name='tarefanotificacao',
            name='uniq_tarefanotificacao_usuario_tarefa',
        ),
        migrations.AddConstraint(
            model_name='tarefanotificacao',
            constraint=models.UniqueConstraint(
                fields=('usuario', 'tarefa', 'tipo'),
                name='uniq_tarefanotificacao_usuario_tarefa_tipo',
            ),
        ),
    ]
