# Generated by Django 5.2.4 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0088_tarefanotificacao_tipo_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefanotificacao',
            name='tarefa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name='notificacoes',
                to='contratos.tarefa',
                verbose_name='Tarefa',
            ),
        ),
        migrations.AddField(
            model_name='tarefanotificacao',
            name='prazo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name='notificacoes',
                to='contratos.prazo',
                verbose_name='Prazo',
            ),
        ),
        migrations.AddConstraint(
            model_name='tarefanotificacao',
            constraint=models.UniqueConstraint(
                fields=('usuario', 'prazo', 'tipo'),
                name='uniq_tarefanotificacao_usuario_prazo_tipo',
            ),
        ),
        migrations.AddConstraint(
            model_name='tarefanotificacao',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(tarefa__isnull=False) & models.Q(prazo__isnull=True))
                    | (models.Q(tarefa__isnull=True) & models.Q(prazo__isnull=False))
                ),
                name='tarefanotificacao_single_target',
            ),
        ),
    ]
