# Generated by Django 5.2.4 on 2026-03-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0089_tarefanotificacao_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadetarefas',
            name='automacao_tipo',
            field=models.CharField(blank=True, choices=[('', 'Sem automação'), ('solicitacao_arquivos_massa', 'Solicitação de arquivos Massa')], default='', max_length=64, verbose_name='Automação'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload'),
        ),
        migrations.CreateModel(
            name='ListaDeTarefasArquivoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do arquivo')),
                ('nome_coluna', models.CharField(blank=True, help_text='Opcional. Se vazio, usa o nome do arquivo.', max_length=120, verbose_name='Coluna da planilha')),
                ('padrao_nome', models.CharField(help_text='Use {contrato} para inserir o número do contrato.', max_length=160, verbose_name='Padrão do nome')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_configurados', to='contratos.listadetarefas', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Configuração de arquivo da lista',
                'verbose_name_plural': 'Configurações de arquivos da lista',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
