# Generated by Codex on 2026-03-23

from django.db import migrations


DEFAULT_FILE_CONFIGS = [
    {
        'nome': 'Contrato',
        'nome_coluna': 'CONTRATO (CFBA)',
        'padrao_nome': '{contrato} - Contrato',
        'ordem': 1,
    },
    {
        'nome': 'Saldo Devedor',
        'nome_coluna': 'SALDO DEVEDOR (BCSUL)',
        'padrao_nome': '{contrato} - Saldo Devedor',
        'ordem': 2,
    },
    {
        'nome': 'Relatório',
        'nome_coluna': 'RELATÓRIO (TOOLS)',
        'padrao_nome': '{contrato} - Relatório',
        'ordem': 3,
    },
    {
        'nome': 'TED',
        'nome_coluna': 'TED (APOIO PRODUÇÃO)',
        'padrao_nome': '{contrato} - TED',
        'ordem': 4,
    },
]

TARGET_LIST_NAMES = {
    'Solicitação de Arquivos C - SD - R - T',
    'Solicitação de arquivos Massa',
}


def seed_solicitacao_arquivos_massa(apps, schema_editor):
    ListaDeTarefas = apps.get_model('contratos', 'ListaDeTarefas')
    ListaDeTarefasArquivoConfig = apps.get_model('contratos', 'ListaDeTarefasArquivoConfig')

    listas = list(ListaDeTarefas.objects.filter(nome__in=TARGET_LIST_NAMES))
    for lista in listas:
        if lista.automacao_tipo != 'solicitacao_arquivos_massa':
            lista.automacao_tipo = 'solicitacao_arquivos_massa'
            lista.save(update_fields=['automacao_tipo'])
        for config in DEFAULT_FILE_CONFIGS:
            ListaDeTarefasArquivoConfig.objects.get_or_create(
                lista=lista,
                nome=config['nome'],
                defaults={
                    'nome_coluna': config['nome_coluna'],
                    'padrao_nome': config['padrao_nome'],
                    'ordem': config['ordem'],
                    'ativo': True,
                },
            )


def unseed_solicitacao_arquivos_massa(apps, schema_editor):
    ListaDeTarefas = apps.get_model('contratos', 'ListaDeTarefas')
    ListaDeTarefasArquivoConfig = apps.get_model('contratos', 'ListaDeTarefasArquivoConfig')

    listas = list(ListaDeTarefas.objects.filter(nome__in=TARGET_LIST_NAMES))
    for lista in listas:
        ListaDeTarefasArquivoConfig.objects.filter(
            lista=lista,
            nome__in=[config['nome'] for config in DEFAULT_FILE_CONFIGS],
        ).delete()
        if lista.automacao_tipo == 'solicitacao_arquivos_massa':
            lista.automacao_tipo = ''
            lista.save(update_fields=['automacao_tipo'])


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0090_listadetarefas_automacao_tipo_tarefa_payload_and_more'),
    ]

    operations = [
        migrations.RunPython(
            seed_solicitacao_arquivos_massa,
            unseed_solicitacao_arquivos_massa,
        ),
    ]
