# Generated by Codex on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0091_seed_solicitacao_arquivos_massa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefanotificacao',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload'),
        ),
    ]
