# Generated by Django 5.2.4 on 2026-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0094_userslackconfig_analysis_type_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefanotificacao',
            name='tipo',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('devolutiva', 'Devolutiva'), ('mencao', 'Menção')], db_index=True, default='recebida', max_length=20, verbose_name='Tipo'),
        ),
    ]
